name: Release

on:
  push:
    branches: [ "master" ]
    paths:
    - "data/**"
    - ".github/**"
  workflow_dispatch:

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install
          yarn build
          gh release create $(date +'%Y.%m.%d-%H%M%S') public/*
      - name: Delete History Release
        uses: sgpublic/delete-release-action@v1.1
        with:
          release-drop: true
          release-keep-count: 5
          release-drop-tag: true
          draft-drop: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image and push
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          GITHUB_USERNAME: ${{ github.actor }}
        run: |
          IMAGE_VERSION=`cat package.json | jq -r '.version'`
          echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/vcards:$IMAGE_VERSION .
          docker tag $DOCKER_USERNAME/vcards:$IMAGE_VERSION $DOCKER_USERNAME/vcards:latest
          docker push $DOCKER_USERNAME/vcards:$IMAGE_VERSION
          docker push $DOCKER_USERNAME/vcards:latest
          
          echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
          docker build -t ghcr.io/$GITHUB_USERNAME/vcards:$IMAGE_VERSION .
          docker tag ghcr.io/$GITHUB_USERNAME/vcards:$IMAGE_VERSION ghcr.io/$GITHUB_USERNAME/vcards:latest
          docker push ghcr.io/$GITHUB_USERNAME/vcards:$IMAGE_VERSION
          docker push ghcr.io/$GITHUB_USERNAME/vcards:latest
